# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Sample workflow for building and deploying a Astro site to GitHub Pages
name: Deploy website to Pages

on:
  schedule:
    - cron: '0 2 * * *'  # Запускается в 2 по гринвичу принулительно
  workflow_run:
    workflows: ["Generate Astro Files from XML"]  # Замените на имя вашего рабочего процесса обновления АВН
    types:
      - completed
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - '.github/workflows/update_cars.yml'
      - '.github/scripts/getOneXML.py'
      - '.github/scripts/update_cars_avito.py'
      - '.github/scripts/update_cars_carcopy.py'
      - '.github/scripts/update_cars_maxposter.py'
      - '.github/scripts/update_cars_vehicles.py'
      - '.github/scripts/update_cars.py'
      - '.github/scripts/config.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    # Указываете окружение и его переменные
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine changes
        id: check_changes
        run: |
          # Проверка запущен ли экшн вручную или есть ли коммиты за последние 10 минут
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "Run manually. Assuming changes." && echo "changes=true" >> $GITHUB_OUTPUT
          else
            COUNT=$(git rev-list --count HEAD --since="10 minutes ago")
            if [ "$COUNT" -eq "0" ]; then
              echo "No new commits. Exiting workflow." && echo "changes=false" >> $GITHUB_OUTPUT
              exit 0
            else
              echo "New commits found." && echo "changes=true" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Setup Pages
        id: pages
        if: steps.check_changes.outputs.changes == 'true'
        uses: actions/configure-pages@v4

      - name: Create env file
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          touch .env
          echo PUBLIC_YANDEX_SITE_VERIFICATION=${{ vars.PUBLIC_YANDEX_SITE_VERIFICATION }} >> .env
          echo PUBLIC_GOOGLE_SITE_VERIFICATION=${{ vars.PUBLIC_GOOGLE_SITE_VERIFICATION }} >> .env
          cat .env

      - name: Download JSONs
        run: |
          mkdir src/data
          curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/banners.json -o src/data/banners.json
          curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/models.json -o src/data/models.json
          curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/salons.json -o src/data/salons.json
          curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/services.json -o src/data/services.json
          curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/socials.json -o src/data/socials.json
          if curl --output /dev/null --silent --fail -r 0-0 ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/cars.json; then
            curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/cars.json -o src/data/cars.json 
          fi
          if curl --output /dev/null --silent --fail -r 0-0 ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/special-services.json; then
            curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/special-services.json -o src/data/special-services.json 
          fi
          if curl --output /dev/null --silent --fail -r 0-0 ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/faq.json; then
            curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/faq.json -o src/data/faq.json 
          fi
          if curl --output /dev/null --silent --fail -r 0-0 ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/reviews.json; then
            curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/reviews.json -o src/data/reviews.json 
          fi
          if curl --output /dev/null --silent --fail -r 0-0 ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/models-sections.yml; then
            curl ${{ secrets.JSON_PATH }}/${{ github.event.repository.name }}/data/models-sections.yml -o src/data/models-sections.yml 
          fi
          ls -al src/data

      - name: Replace Placeholders in JSON
        run: |
          node .github/scripts/replacePlaceholdersInJson.js

      - name: Build Astro
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm build --outDir ./_site

      - name: Upload artifact
        if: steps.check_changes.outputs.changes == 'true'
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3

    outputs:
      changes: ${{ steps.check_changes.outputs.changes }}

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.changes == 'true'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  notify_telegram:
    needs: deploy
    if: needs.build.outputs.changes == 'true'
    uses: ./.github/workflows/github-telegram.yml
    with:
      additional-text: $(echo -n 'After deploy' | base64)
    secrets:
      TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
